# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Introdução a utilização de BD em Python II
#Importando os módulos 
import sqlite3 
import random
import time
import datetime

con = sqlite3.connect("banco.db") #Criando o BD caso ele não exista

cur = con.cursor() #Criando um cursor (Percorrer os registros)

# Função para criar uma tabela
def create_table():
  cur.execute('CREATE TABLE IF NOT EXISTS produtos(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, date TEXT, '\
              'prod_name TEXT, valor REAL)')

# Função para inserir uma linha
def data_insert():
  cur.execute("INSERT INTO produtos VALUES (10, '2019-11-13 12:09:23', 'Teclado', 90)")
  con.commit()
  cur.close()
  con.close() 

# Usando variáveis para inserir dados
def data_insert_var():
  cur = con.cursor()
  new_date = datetime.datetime.now()
  new_prod_name = 'Monitor'
  new_valor = random.randrange(50,100)  
  cur.execute("INSERT INTO produtos (date, prod_name, valor) VALUES (?,?,?)", (new_date, new_prod_name, new_valor))
  con.commit()

#Leitura de dados
def leitura_todos_dados():
  cur = con.cursor()
  cur.execute("SELECT * FROM produtos")
  for linha in cur.fetchall():
    print(linha)

#Leitura de registros específicos
def leitura_registros():
  cur = con.cursor()
  cur.execute("SELECT * FROM produtos WHERE valor > 60.0")
  for linha in cur.fetchall():
    print(linha)

#Leitura de colunas específicas
def leitura_colunas():
  cur = con.cursor()
  cur.execute("SELECT * FROM produtos")
  for linha in cur.fetchall():
    print(linha[3])

#Update
def atualiza_dados():
  cur = con.cursor()
  cur.execute(" UPDATE produtos SET valor = 60.00 WHERE valor = 81.0")
  con.commit()

#Delete
def remove_dados():
  cur = con.cursor()
  cur.execute("DELETE FROM produtos WHERE valor = 60.0")
  con.commit()

# Criar tabela
create_table()

# Inserir dados
data_insert()

# Gerando valores e inserindo na tabela
for i in range(10):
  data_insert_var()
  time.sleep(1)

#Select nos dados
leitura_todos_dados()

#Leitura de registros especificos
leitura_registros()

#Leitura de colunas especificas
leitura_colunas()

#Atualiza dados
atualiza_dados()

#Delete dados
remove_dados()

con.close()