# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

from pymongo import MongoClient

conn = MongoClient('localhost', 27017)

type(conn)

#Uma única instância do MongoDB pode suportar diversos banco de dados
#Vamos criar o banco de dados cadastrodb
db = conn.cadastrodb

#Uma coleção é um grupo de documentos armazenados no Mongo DB
#É relativamente parecido com o conceito de tabelas em bancos relacionais
collection = db.cadastrodb

type(collection)

import datetime
#Dados no MongoDB são representados(e armazenados) usando documentos JSON
#Com o PyMOngo usamos dicionarios para representar documentos.

post1 = {"codigo": "ID-9987725",
         "prod_name": "Geladeira",
         "marcas": ["brastemp","consul", "electrolux"],
         "data_cadastro": datetime.datetime.utcnow()}

type(post1)

collection = db.posts

post_id = collection.insert_one(post1)

post_id.inserted_id

post_id

post2 = {"codigo": "ID-22098765",
         "prod_name": "Televisor",
         "marcas": ["samsung","panasonic", "lg"],
         "data_cadastro": datetime.datetime.utcnow()}

collection = db.posts

post_id = collection.insert_one(post2).inserted_id

post_id

collection.find_one({"prod_name":"Televisor"})

#A função find() retorna um cursor e podemos então navegar pelos dados
for post in collection.find():
  print(post)

#Verificando o nome do banco de dados
db.name

#Listando as coleções disponiveis
db.collection_names()